const IPC_READY = 'IPC_READY'
const IPC_READY_REPLY = 'IPC_READY_REPLY'
const IPC_OPEN_FILE = 'IPC_OPEN_FILE'
const IPC_OPEN_FILE_REPLY = 'IPC_OPEN_FILE_REPLY'
const IPC_OPEN_DIR = 'IPC_OPEN_DIR'
const IPC_OPEN_DIR_REPLY = 'IPC_OPEN_DIR_REPLY'

module.exports = {
  IPC_READY,
  IPC_READY_REPLY,
  IPC_OPEN_FILE,
  IPC_OPEN_FILE_REPLY,
  IPC_OPEN_DIR,
  IPC_OPEN_DIR_REPLY
}
